import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import BackgroundVideo from "./components/BackgroundVideo";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
    readonly children: React.ReactNode
} 

export default function RootLayout({
  children,
}: RootLayoutProps ) {
  return (
    <html lang="en">
      <body className="page relative">
        <BackgroundVideo />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}