import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
    readonly children: React.ReactNode
} 

export default function RootLayout({
  children,
}: RootLayoutProps ) {
  return (
    <html lang="en">
      <body className="page">
        <Navbar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
